website/auth.py
from cgi import print_exception
from curses.ascii import isblank
from posixpath import basename
from unicodedata import category
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Cart, User,Book, Order, Note
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

def add_manager():
    # create manager accounts
    manager = User(
        email ='manager@uab.edu',
        password = generate_password_hash('1234567', method='sha256'),
        first_name = 'Tim',
        last_name='Brown',
        role ='manager')
    manager1 = User(
        email ='manager1@uab.edu', 
        password =generate_password_hash('1234567', method='sha256'),
        first_name = 'Alex',
        last_name='Johnston',
        role ='manager')
    db.session.add(manager)
    db.session.add(manager1)
    db.session.commit()
    print("Manager accounts, manger@uab.edu and manager1@uab.edu created!")



@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                if user.role=="manager":
                    print("Manager",email, 'logged in.')
                    return redirect(url_for('views.manager_acc'))
                print("a non-manger customer logged in.")
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastname')
        role ="customer"
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        print("first name:",first_name,"last name:",last_name,'password1',password1,"role",role)
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif len(last_name) < 2:
            flash('Last name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, last_name=last_name, role=role, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            m_accounts = User.query.filter_by(role='manager').all()
            if len(m_accounts)<1:
                add_manager()
            login_user(new_user, remember=True)
            if role=="manager":
                print("Manager",email, 'signed up.')
                flash('Manager account created!', category='success')
                return redirect(url_for('views.manager_acc'))
            else:    
                print("A new customer signed up.")
                flash('customer account created!', category='success')
                return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

@auth.route("/add_book",methods=['POST','GET'])
@login_required
def add_book():
    if request.method=='POST':
        bname=request.form.get('bname')
        authors=request.form.get('authors')
        category=request.form.get('category')
        ISBN=request.form.get('ISBN')
        price  = request.form.get('price')
        qty = request.form.get('qty')
        new_book = Book(bname=bname,authors=authors,category=category,ISBN=ISBN,price=price,qty=qty)
        db.session.add(new_book)
        db.session.commit()
        flash('New Book Added','success')
        return redirect(url_for("views.manager_acc"))
    return redirect(url_for("views.manager_acc"))

@auth.route("/edit_book/<string:ISBN>",methods=['POST','GET'])
@login_required
def edit_book(ISBN):
    print("Editing Book:",ISBN)
    if request.method=='POST':
        price=request.form.get('price')
        stock=request.form.get('qty')
        book = Book.query.filter_by(ISBN=ISBN).first_or_404()
        book.price=price
        book.qty=stock
        db.session.commit()
        flash('Book updated','success')
        return redirect(url_for("views.manager_acc"))
    book = Book.query.filter_by(ISBN=ISBN).first_or_404()
    print("book",book)
    return render_template("edit_book.html", user=current_user,datas=book)


@auth.route("/delete_book",methods=['GET'])
def delete_book():
    ISBN = request.args.get("ISBN")
    print("Deleting book ISBN =",ISBN)
    book = Book.query.filter_by(ISBN=ISBN).first_or_404()
    db.session.delete(book)
    db.session.commit()
    flash('Book Deleted','warning')
    return redirect(url_for("views.home",user=current_user))

@auth.route("/add_to_cart/<string:ISBN>",methods=['POST','GET'])
@login_required
def add_to_cart(ISBN):
    print("add_to_cart started",ISBN)
    print(request.method)
    if request.method=='POST':
        numb = request.form.get('qty')
        book =Book.query.filter_by(ISBN=ISBN).first()
        cart_book = Cart(bname=book.bname,authors=book.authors,category=book.category,ISBN=ISBN,price=book.price,qty=numb,user_id=current_user.id)
        # check if the book already in cart
        #book_ck = Cart.query.filter_by(ISBN =ISBN,user_id = current_user.id).first()
        #if 
        db.session.add(cart_book)
        db.session.commit()
        flash("Book added sucessfully")
        return redirect(url_for("views.home",user=current_user))
    print("add_to_cart ran")
    book =Book.query.filter_by(ISBN=ISBN).first()
    return render_template("add_to_cart.html",user=current_user, book = book)


@auth.route("/checkout/<float:total>",methods=['POST','GET'])
@login_required
def checkout(total): 
    # put order infor to Order
    # reduce stock qty
    # direct to thankyou page
    print('start checkout...')
    total = round(total,2)
    if request.method=='POST':
        orders= db.session.query(Order).all()
        print("find previous orders:",orders)
        if not orders:
            order_numb = 101
        else:
            last_order=db.session.query(Order).order_by(Order.oid.desc()).first()
            print("last order number:",last_order.onumb)
            order_numb =last_order.onumb + 1
        print('Order number:', order_numb)
        for book in current_user.cart:
            bname = book.bname
            authors = book.authors
            category=book.category
            ISBN=book.ISBN
            price=book.price
            qty = book.qty
            user_id=current_user.id

            bk_stock = Book.query.filter_by(ISBN = ISBN).first_or_404()
            bk_stock.qty-=qty
            if bk_stock.qty < 1:
                flash("Sorry, there\'s no enough stock for this book: "+ bname+". Please adjust your cart.",'warning')
                return render_template("display_cart.html", user=current_user)
            else:
                item=Order(onumb=order_numb,bname=bname,authors=authors,category=category,ISBN=ISBN,price=price,qty=qty,order_total = total, user_id=user_id)
                db.session.add(item)
                db.session.commit()
        Cart.query.filter_by(user_id=current_user.id).delete()
        db.session.commit()
        # send a message to managers
        managers = User.query.filter_by(role="manager").all()
        for manager in managers:
            note = Note(order_number= order_numb,user_id=manager.id)
            db.session.add(note)
            db.session.commit()
            print("note added to manager",manager,manager.email)
        flash('Order completed','success')
        return render_template("thankyou.html",user=current_user)
    return render_template("checkout.html", user=current_user)



""" @auth.route("/edit_cart",methods=['POST','GET'])
@login_required
def edit_cart():
    if request.method=='POST':
        Cart.query.delete() # empty the cart first
        new_cart = request.args.get("cart")
        for book in new_cart:
            add_book=Cart(bname=book.bname,authors=book.authors,category=book.category,ISBN=book.ISBN,price=book.price,qty=book.qty)
            db.session.add(add_book)
            db.session.commit()
        flash("Cart updated sucessfully")
        return redirect(url_for("views.home",user=current_user))
    return redirect(url_for("views.home",user=current_user)) """

website/views.py
from unicodedata import category
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Book,Cart, Order,Note,User
from sqlalchemy import delete
from sqlalchemy.sql import func
from . import db
import json


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    bklist = db.session.query(Book).all()
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    return render_template("home.html", user=current_user, bklist=bklist,date=date)

@views.route('/show_books/<string:choice>', methods=['GET'])
@login_required
def show_books(choice):
    print("Category selected:",choice)
    if choice =="All":
        bklist = db.session.query(Book).all()
    else:
        bklist = Book.query.filter_by(category=choice).all()
    return render_template("home.html", user=current_user, bklist=bklist)


@views.route('/display_cart', methods=['GET', 'POST'])
@login_required
def display_cart():
    print("Displaying cart for user id:", current_user.id)
    cart = Cart.query.filter_by(user_id=current_user.id).first()
    print(current_user.id)
    return render_template("display_cart.html", user=current_user,cart=cart)


@views.route('/empty-cart', methods=['POST'])
@login_required
def empty_cart():
    dele = Cart.delete().where(Cart.c.user_id==current_user.id)
    dele.execute()
    flash("Cart Empted!","warning")
    books = db.session.query(Book).all()
    return render_template("home.html", user=current_user,bklist=books)

@views.route("/delet_from_cart",methods=['GET'])
@login_required
def delete_from_cart():
    ISBN = request.args.get('ISBN')
    print("Removing book from cart with ISBN:", ISBN)
    book = Cart.query.filter_by(ISBN=ISBN,user_id= current_user.id).first()
    db.session.delete(book)
    db.session.commit()
    flash("Book removed from your cart.",'warning')
    return render_template("display_cart.html",user=current_user)


@views.route('/order_history', methods=['GET'])
@login_required
def order_history():
    if current_user.role=='manager':
        orders = Order.query.all()
        users=User.query.all()
        return render_template("order_history.html", user=current_user, users=users,orders = orders)
    else:
        return render_template("order_history.html", user=current_user, users=current_user,orders = current_user.order)

@views.route('/user_profile', methods=['GET'])
@login_required
def user_profile():
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    return render_template("user_profile.html", user=current_user,date=date)

@views.route('/manager_acc', methods=['GET', 'POST'])
@login_required
def manager_acc():
    bklist = db.session.query(Book).all()

    return render_template("manager.html", user=current_user, bklist=bklist, order = Order)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@views.route("/aboutus")
def about_us():
    return render_template("./about_us.html",user=current_user)

website/templates/About_us.html
{%extends "base.html" %}
{%block title %}About us{% endblock %}

{% block content %}   

<div class = "container">
<h3>Bookstore physical address</h3>
<address>Hill Student Center, Birmingham, AL 35226</address>

<h3>Contact us</h3>
<p>Phone: 205-111-2222 (fake)</p>
<email>bookstore_test@uab_test.edu</email>

<h3>Hour of Operation</h3>
<ul>
    <li>Sunday: Closed</li>
    <li>Monday: 8am to 4pm</li>
    <li>Tuesday: 8am to 4pm</li>
    <li>Wednesday: 8am to 4pm</li>
    <li>Thursday: 8am to 4pm</li>
    <li>Friday: 8am to 4pm</li>
    <li>Saturday: Closed</li>
</ul>


<br>
<br>
<br>
<h3>How to order books at UAB bookstore</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/g5lFSxWfht0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<div class = "container">
<figcaption>Video referenced from youtube: keyworld UAB bookstore</figcaption>



</div>

{% endblock %}

website/templates/add_to_cart.html
{% extends "base.html" %} {% block title %}Edit Student record{% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>Add Book to Cart</h4>
  <div class='row'>
    <div class='col-5 mx-auto'>
      <h3>Add Book to Cart</h3><hr>
      <form method='post' action='{{url_for("auth.add_to_cart",ISBN=book.ISBN)}}'>
        <p>Title: {{book.bname}} </p>
        <p>Authors: {{book.authors}} </p>
        <p>ISBN: {{book.ISBN}} </p>
        <p>Price: {{book.price}} </p>
        <div class='form-group'>
          <label>Enter quantity</label>
          <input type='integer' name='qty'  required class='form-control' required class='form-control' value='1'>
        </div>
        <input type='submit' value='Submit' class='btn btn-primary'>
      </form>
    </div>
  </div>
</div>
{% endblock %}

website/templates/checkout.html
{% extends "base.html" %} {% block title %}Checkout{% endblock %}

{% block content  %}
<div class="jumbotron">
  <h4 class='text-center text-muted mb-3'>Checkout</h4>

  <div class='container'>
      <h4>1. Shipping Address</h4><hr>
      <form method="post" action="#" class='text-center' >
        <label for="name"></label><input type="text" name ="name" placeholder="Full name">
        <label for="address" ></label> <input type="text" name ="address" placeholder="Street address">
        <label for="city" ></label> <input type="text" name ="city" placeholder="City">
        <label for="zip" ></label> <input type="integer" name ="zip" placeholder="Zip code">
      </form>
  </div>

  <div class='container'>
      <h4>2. Payment Methods</h4><hr>
      <h5>Biling address (if different from shipping address)</h5>
      <form method="post" action="#" class='text-center' >
        <label for="name"></label><input type="text" name ="name" placeholder="Full name">
        <label for="address" ></label> <input type="text" name ="address" placeholder="Street address">
        <label for="city" ></label> <input type="text" name ="city" placeholder="City">
        <label for="zip" ></label> <input type="integer" name ="zip" placeholder="Zip code">
      </form>
      <h5>Credit card information</h5>
      <form method="post" action="#" class='text-center' >
        <label for="Card#"></label><input type="integer" name ="Card#" placeholder="Card number">
        <label for="exp" ></label> <input type="integer" name ="exp" placeholder="Expiration (MMYY)">
        <label for="CSC" ></label> <input type="integer" name ="csc" placeholder="sec code">
      </form>
  </div>


  <h4>3. Review items</h4><hr>
  <table class='table table-bordered'>
      <thead>
        <th>Book Title</Title></th>
        <th>Authors</th>
        <th>ISBN</th>
        <th>Category</th>
        <th>Price</th>
        <th>qty</th>
      </thead>
      <tbody>
        {% set t = namespace(sum = 0) %}
        {% for book in user.cart %}
          <tr>
            <td>{{book.bname}}</td>
            <td>{{book.authors}}</td>
            <td>{{book.ISBN}}</td>
            <td> {{book.category}} </td>
            <td> {{book.price}} </td>
            <td> {{book.qty}} </td>
          </tr>
          {% set t.sum =t.sum + book.price*book.qty %}
        {%endfor%}
      </tbody>
    </table>
    <hr><hr>
  <div class = "container">
    <form method="post" action='{{url_for("auth.checkout",total=t.sum+t.sum*0.05,cart=user.cart)}}' >
      <p>Items Total: {{"$%.2f"|format(t.sum)}}</p>
      <p>Estimated tax:  {{"$%.2f"|format(t.sum*0.05)}}</p>
      <p><b>Order total:  {{"$%.2f"|format(t.sum+t.sum*0.05)}}</b> </p>
      <input type='submit' value='Submit' class='btn btn-primary'>
  </form>
  </div>
</div>
{% endblock %}

website/templates/display_cart.html
{% extends "base.html" %} {% block title %}Shopping cart{% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>Your Cart</h4>
  <div class='row'>
    <table class='table table-bordered'>
      <thead>
        <th>Book Title</Title></th>
        <th>Authors</th>
        <th>ISBN</th>
        <th>Category</th>
        <th>Price</th>
        <th>qty</th>
     
        <th>Delete</th>
      </thead>
      <tbody>
        {% set t = namespace(sum = 0) %}
        {% for book in user.cart %}
          <tr>
            <td>{{book.bname}}</td>
            <td>{{book.authors}}</td>
            <td>{{book.ISBN}}</td>
            <td> {{book.category}} </td>
            <td> {{book.price}} </td>
            <td> {{book.qty}} </td>
            
           <td><a href='{{url_for("views.delete_from_cart",ISBN=book.ISBN)}}' class='btn btn-primary' onclick='return confirm("Are You Sure? ")'>Delete</a> </td> 
          </tr>
          {% set t.sum =t.sum + book.price*book.qty %}
        {%endfor%}
      </tbody>
    </table>
    <p>Cart Total: {{"$%.2f"|format(t.sum)}}</p><br>
    <hr>
    <div>
      <a href='{{url_for("auth.checkout",total=t.sum)}}' class='btn btn-primary' '>Checkout</a> 
    </div>
    
</div>
{% endblock %}

website/templates/edit_book.html
{% extends "base.html" %} {% block title %}Update Book record{% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>Update book information</h4>

      <h3>Update Book infromation</h3><hr>
      <form method='post' action='{{url_for("auth.edit_book",ISBN=datas.ISBN)}}'>
        <p><b>Title:</b>&nbsp; {{datas.bname}}</p>
        <p><b>Authors:</b>&nbsp; {{datas.authors}}</p>
        <p><b>Category:</b>&nbsp; {{datas.category}}</p>
        <p><b>ISBN:</b>&nbsp; {{datas.ISBN}}</p>
        <div class='form-group'>
            <p><b>price</b>
            <input type='float' name='price' required class='form-control' value='{{datas.price}}'></p>
 
            <p><b>Quntity</b>
            <input type='Integer' name='qty' required class='form-control' value='{{datas.qty}}'></p>
          </div>
          <input type='submit' value='Submit' class='btn btn-primary'>
      </form>


</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content%}
<a href='{{url_for("views.user_profile")}}'  class='btn btn-outline-dark float-left' >User Profile </a>

<div class="jumbotron">
  {% set len = namespace(n_book =0) %}
  {% set t = namespace(sum =0) %}
  {% if user.cart is defined and user.cart|length > 0 %}
    {% for book in user.cart %}
     {% set len.n_book = len.n_book +1 %}
     {% set t.sum =t.sum + book.price*book.qty %}
    {% endfor %}
  {% endif %}

  <a href='{{url_for("views.display_cart")}}'  class='btn btn-primary float-right' >Your Cart ({{len.n_book}}, {{"$%.2f"|format(t.sum)}}) </a>
  <a href='{{url_for("views.order_history")}}'  class='btn btn-outline-dark float-right' >Order History </a>


  <h1 align="center"> Welcome to UAB Bookstore</h1>


  <h4 class='text-center text-muted mb-3'>Book List</h4>

  <div class="dropdown">
    <button class="dropbtn">Select a category</button>
    <div class="dropdown-content">
      <a href='{{url_for("views.show_books",choice="All")}}' class='btn btn-primary'>All</a>
      <a href='{{url_for("views.show_books",choice="Adventure")}}' class='btn btn-primary'>Adventure</a>
      <a href='{{url_for("views.show_books",choice="Fictionary")}}' class='btn btn-primary'>Fictionary</a>
      <a href='{{url_for("views.show_books",choice="Scientific")}}' class='btn btn-primary'>Scientific</a>
      <a href='{{url_for("views.show_books",choice="History")}}' class='btn btn-primary'>History</a>
    </div>
  </div>


  <table class='table table-bordered' >
    <thead>
      <th>Book Title</th>
      <th>Authors</th>
      <th>ISBN</th>
      <th>Category</th>
      <th>Price</th>
      <th>Stock qty</th>
      <th>Add to cart</th>
    </thead>
    <tbody>
      {% for book in bklist %}
        <tr>
          <td>{{book.bname}}</td>
          <td>{{book.authors}}</td>
          <td>{{book.ISBN}}</td>
          <td>{{book.category}} </td>
          <td>{{book.price}} </td>
          <td>{{book.qty}} </td>
          <td><a href='{{url_for("auth.add_to_cart",ISBN=book.ISBN)}}' class='btn btn-primary'>Add to Cart</a></td>
        </tr>
      {%endfor%}
    </tbody>
  </table>

</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<div class="jumbotron">
  <form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
</div>
{% endblock %}

website/templates/manager.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content%}

<a href='{{url_for("views.user_profile")}}'  class='btn btn-outline-dark float-left' >User Profile </a>


<div class="jumbotron">

  <a href='{{url_for("views.order_history")}}'  class='btn btn-outline-dark float-right' >See Orders</a>

  <h2 align="center"> Welcome to UAB Bookstore Manager Page</h2>

<div class="container">
  <h4 align="left">Order notification</h4>
  <ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
    <li class="list-group-item">
      <p> A new order (#{{ note.order_number }} ) is placed! </p>
      <button type="button" class="close" onClick="deleteNote({{ note.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
    </li>
    {% endfor %}
  </ul>
</div>
<div class="container">
  <h4>Add books to the store</h4>
  
  <form method="post" action="{{url_for('auth.add_book')}}" class='text-center' >
    <label for="bname"></label><input type="text" name ="bname" placeholder="Book Title" style="width: 400px;">
    <label for="authors" ></label> <input type="text" name ="authors" placeholder="Authors" style="width: 150px;">
    <label for="category" ></label> <input type="text" name ="category" placeholder="Category" style="width: 100px;"> 
    <label for="ISBN" ></label> <input type="text" name ="ISBN" placeholder="ISBN" style="width: 100px;">
    <label for="price" ></label> <input type="float" name ="price" placeholder="Price" style="width: 70px;">
    <label for="qty" ></label> <input type="integer" name ="qty" placeholder="Quantity" style="width: 70px;">
    <input type="submit" class='btn btn-success' value="+Add">
  </form>

  <br><br>
  <h3 class='text-center '>Book List</h3>
</div>
  <div class="dropdown">
    <button class="dropbtn">Select a category</button>
    <div class="dropdown-content">
      <a href='{{url_for("views.show_books",choice="All")}}' class='btn btn-primary'>All</a>
      <a href='{{url_for("views.show_books",choice="Adventure")}}' class='btn btn-primary'>Adventure</a>
      <a href='{{url_for("views.show_books",choice="Fictionary")}}' class='btn btn-primary'>Fictionary</a>
      <a href='{{url_for("views.show_books",choice="Scientifc")}}' class='btn btn-primary'>Scientifc</a>
      <a href='{{url_for("views.show_books",choice="History")}}' class='btn btn-primary'>History</a>
    </div>
  </div>

  <table class='table table-bordered' >
    <thead>
      <th>Book Title</th>
      <th>Authors</th>
      <th>ISBN</th>
      <th>Category</th>
      <th>Price</th>
      <th>Stock qty</th>
      <th>Add to cart</th>
    </thead>
    <tbody>
      {% for book in bklist %}
        <tr>
          <td>{{book.bname}}</td>
          <td>{{book.authors}}</td>
          <td>{{book.ISBN}}</td>
          <td>{{book.category}} </td>
          <td>{{book.price}} </td>
          <td>{{book.qty}} </td>
          <td><a href='{{url_for("auth.edit_book",ISBN=book.ISBN)}}' class='btn btn-primary'>Edit</a></td>
        </tr>
      {%endfor%}
    </tbody>
  </table>

</div>

{% endblock %}

website/templates/order_history.html
{% extends "base.html" %} {% block title %}Order history{% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>Order history</h4>
    <hr>
  <div class='row'>
    {% set order = namespace(n = 1) %}
    {% set name = namespace(first = "first") %}
    {% set name = namespace(last = "last") %}
    {% for row in orders %}
        {% if order.n != row.onumb %}
            {% set order.n = row.onumb %}
            {% if users == current_user %}
              {% set name.first = current_user.first_name %}
              {% set name.last = current_user.last_name %}
            {% else %}
                {% for user in users %}
                    {% if user.id == row.user_id %} 
                      {% set name.first = user.first_name %}
                      {% set name.last = user.last_name %}
                    {% endif %}
                {% endfor %}
            {% endif %}
            <p> <b> Order # {{row.onumb}}: </b> </p>
            <p> &nbsp;Order placed on: {{row.date}}.  Order total: {{"$%.2f"|format(row.order_total)}}.  Placed by user #{{row.user_id}}, {{name.first}} {{name.last}}. </p>
        {% endif %}
        <div  class="container">
          <p><b>Title: </b> {{row.bname}}.&nbsp;
            <b>Authors: </b> {{row.authors}}.&nbsp;
            <b>ISBN:</b> {{row.ISBN}}.&nbsp;
            <b>Price: </b> {{"$%.2f"|format(row.price)}}.&nbsp;
            <b>Quantity: </b> {{row.qty}}.
          </p>
        </div>
        <hr>
    {% endfor %}
  </div>

</div>
{% endblock %}

website/templates/thankyou.html
{% extends "base.html" %} {% block title %}Thank you {% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>Thanks for your order! Please come back again.</h4>
</div>
</div>
{% endblock %}

website/templates/user_profile.html
{% extends "base.html" %} {% block title %}User Profile{% endblock %}

{% block content  %}
<div class="jumbotron">
    <h4 class='text-center text-muted mb-3'>User Profile</h4>
    <hr>
    <h3>Hello, {{user.first_name}}! </h3><hr>
      
    <p><b>First name:</b>&nbsp; {{user.first_name}}</p>
    <p><b>Last name:</b>&nbsp; {{user.last_name}}</p>
    <p><b>Email address:</b>&nbsp; {{user.email}}</p>
    <p><b>Role:</b>&nbsp; {{user.role}}</p>
    <p><b>Account created:</b>&nbsp; {{user.date.date()}}</p>

</div>
{% endblock %}